from machine import Machine

m = Machine()
m.setTape(["a","a","b","b","c","c",""])

# (q0,a)=(q1,x,>)
m.setRule("q0","a","q1","x",">")
# (q1,a)=(q1,a,>)
m.setRule("q1","a","q1","a",">")
# (q1,y)=(q1,y,>)
m.setRule("q1","y","q1","y",">")
# (q1,b)=(q2,y,>)
m.setRule("q1","b","q2","y",">")
# (q2,b)=(q2,b,>)
m.setRule("q2","b","q2","b",">")
# (q2,z)=(q2,z,>)
m.setRule("q2","z","q2","z",">")
# (q2,c)=(q3,z,<)
m.setRule("q2","c","q3","z","<")
# (q3,b)=(q3,b,<)
m.setRule("q3","b","q3","b","<")
# (q3,y)=(q3,y,<)
m.setRule("q3","y","q3","y","<")
# (q3,a)=(q3,a,<)
m.setRule("q3","a","q3","a","<")
# (q3,z)=(q3,z,<)
m.setRule("q3","z","q3","z","<")
# (q3,x)=(q0,x,>)
m.setRule("q3","x","q0","x",">")
# (q0,y)=(q4,y,>)
m.setRule("q0","y","q4","y",">")
# (q4,y)=(q4,y,>)
m.setRule("q4","y","q4","y",">")
# (q4,z)=(q5,z,>)
m.setRule("q4","z","q5","z",">")
# (q5,z)=(q5,z,>)
m.setRule("q5","z","q5","z",">")
# (q5,_)=(q6,_,>)
m.setRule("q5","","q6","",">")
m.setAccept("q6")

print(m.tape)
print("status ",m.run())
print(m.tape)