from machine import Machine

m = Machine()
m.setTape(["a","b","a","a","b","a",""])

# (q0,a)=(q1,x,>)
m.setRule("q0","a","q1","x",">")
# (q1,a)=(q1,a,>)
m.setRule("q1","a","q1","a",">")
# (q1,b)=(q1,b,>)
m.setRule("q1","b","q1","b",">")
# (q1,x)=(q1,x,>)
m.setRule("q1","x","q1","x",">")
# (q1,y)=(q1,y,>)
m.setRule("q1","y","q1","y",">")
# (q1,_)=(q3,_,<)
m.setRule("q1","","q3","","<")
# (q3,x)=(q3,x,<)
m.setRule("q3","x","q3","x","<")
# (q3,y)=(q3,y,<)
m.setRule("q3","y","q3","y","<")
# (q3,a)=(q5,x,<)
m.setRule("q3","a","q5","x","<")
# (q5,a)=(q5,a,<)
m.setRule("q5","a","q5","a","<")
# (q5,b)=(q5,b,<)
m.setRule("q5","b","q5","b","<")
# (q5,x)=(q0,x,>)
m.setRule("q5","x","q0","x",">")
# when q0 -> q2

# (q0,b)=(q2,y,>)
m.setRule("q0","b","q2","y",">")
# (q2,a)=(q2,a,>)
m.setRule("q2","a","q2","a",">")
# (q2,b)=(q2,b,>)
m.setRule("q2","b","q2","b",">")
# (q2,x)=(q2,x,>)
m.setRule("q2","x","q2","x",">")
# (q2,y)=(q2,y,>)
m.setRule("q2","y","q2","y",">")
# (q2,_)=(q4,_,<)
m.setRule("q2","","q4","","<")
# (q4,x)=(q4,x,<)
m.setRule("q4","x","q4","x","<")
# (q4,y)=(q4,y,<)
m.setRule("q4","y","q4","y","<")
# (q4,b)=(q6,y,<)
m.setRule("q4","b","q6","y","<")
# (q6,a)=(q6,a,<)
m.setRule("q6","a","q6","a","<")
# (q6,b)=(q6,b,<)
m.setRule("q6","b","q6","b","<")
# (q6,y)=(q0,y,>)
m.setRule("q6","y","q0","y",">")

m.setAccept("q0")

print(m.tape)
print("status ",m.run())
print(m.tape)